# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/pylint
    rev: v2.15.6
    hooks:
    -   id: pylint
        language: system
        args:
        - --max-line-length=120
        - --output-format=colorized
        - --errors-only
