apiVersion: v1
kind: Service
metadata:
  name: "shop-service"
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 5000

    protocol: TCP
  sessionAffinity: "ClientIP"
  selector:
    app: shop-app
