name: Publish Docker image
on:
    push:
        branches: [ main, Dev ]
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: Get branch name
                run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN}}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: shop_app:${{ env.BRANCH }}_${{ github.sha }}
