name: Publish Docker image
on:
    push:
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: Get branch name
                run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

            -
                name: Set tag
                run: |
                  if [[ "${{ env.BRANCH}}" == 'main']]; then
                    $docker_tag == 'latest'
                  else
                    $docker_tag == ${{ env.BRANCH }}_${{ github.sha }}
                  fi

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to ghcr
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN}}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: ghcr.io/devops-cicd-slutprojekt/shop_app:$docker_tag
